-- fires a bunch of remote events to increased mined amount
-- generated by grok again lolol
local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local UserInputService = game:GetService("UserInputService")

local player = Players.LocalPlayer
local Remotes = ReplicatedStorage:WaitForChild("Remotes")

-- Create GUI
local screenGui = Instance.new("ScreenGui")
screenGui.Name = "MiningSpammer"
screenGui.ResetOnSpawn = false
screenGui.Parent = player:WaitForChild("PlayerGui")

local frame = Instance.new("Frame")
frame.Size = UDim2.new(0, 300, 0, 240)
frame.Position = UDim2.new(0.5, -150, 0.35, 0)
frame.BackgroundColor3 = Color3.fromRGB(20, 20, 26)
frame.BorderSizePixel = 0
frame.Active = true
frame.Draggable = true
frame.Parent = screenGui

Instance.new("UICorner", frame).CornerRadius = UDim.new(0, 16)

-- Title
local title = Instance.new("TextLabel")
title.Size = UDim2.new(1, -55, 0, 40)
title.Position = UDim2.new(0, 15, 0, 5)
title.BackgroundTransparency = 1
title.Text = "⛏️ Mining Spammer"
title.TextColor3 = Color3.fromRGB(235, 235, 245)
title.TextSize = 18
title.Font = Enum.Font.GothamBold
title.TextXAlignment = Enum.TextXAlignment.Left
title.Parent = frame

-- Status
local status = Instance.new("TextLabel")
status.Size = UDim2.new(1, -30, 0, 26)
status.Position = UDim2.new(0, 15, 0, 52)
status.BackgroundTransparency = 1
status.Text = "● Idle"
status.TextColor3 = Color3.fromRGB(170, 170, 180)
status.TextSize = 14
status.Font = Enum.Font.Gotham
status.Parent = frame

-- Toggle Button
local toggle = Instance.new("TextButton")
toggle.Size = UDim2.new(0.88, 0, 0, 55)
toggle.Position = UDim2.new(0.06, 0, 0, 88)
toggle.BackgroundColor3 = Color3.fromRGB(40, 40, 48)
toggle.Text = "ENABLE SPAM"
toggle.TextColor3 = Color3.fromRGB(255, 255, 255)
toggle.TextSize = 16
toggle.Font = Enum.Font.GothamBold
toggle.Parent = frame

Instance.new("UICorner", toggle).CornerRadius = UDim.new(0, 12)

-- Info
local info = Instance.new("TextLabel")
info.Size = UDim2.new(1, -30, 0, 55)
info.Position = UDim2.new(0, 15, 0, 155)
info.BackgroundTransparency = 1
info.Text = "Hold E while enabled to spam all likely mining remotes\nRelease E to stop"
info.TextColor3 = Color3.fromRGB(150, 150, 165)
info.TextSize = 13
info.Font = Enum.Font.Gotham
info.TextWrapped = true
info.TextXAlignment = Enum.TextXAlignment.Left
info.Parent = frame

-- Close Button
local closeBtn = Instance.new("TextButton")
closeBtn.Size = UDim2.new(0, 28, 0, 28)
closeBtn.Position = UDim2.new(1, -36, 0, 8)
closeBtn.BackgroundTransparency = 1
closeBtn.Text = "✕"
closeBtn.TextColor3 = Color3.fromRGB(170, 170, 180)
closeBtn.TextSize = 18
closeBtn.Parent = frame

-- Variables
local enabled = false
local spamming = false
local conn = nil

local function tryFire(remoteName, arg)
    local remote = Remotes:FindFirstChild(remoteName)
    if not remote then return end
    pcall(function()
        if remote:IsA("RemoteFunction") then
            if arg ~= nil then
                remote:InvokeServer(arg)
            else
                remote:InvokeServer()
            end
        elseif remote:IsA("RemoteEvent") then
            if arg ~= nil then
                remote:FireServer(arg)
            else
                remote:FireServer()
            end
        end
    end)
end

local function startSpamming()
    if spamming then return end
    spamming = true
    status.Text = "● SPAMMING ALL"
    status.TextColor3 = Color3.fromRGB(0, 255, 140)

    conn = game:GetService("RunService").Heartbeat:Connect(function()
        -- Most likely to increase mining
        tryFire("DigBlock")
        tryFire("DigBlock", 1)
        tryFire("NukeEffect")
        tryFire("BoostActivated")
        
        -- Reward / Cash related
        tryFire("AdminCash")
        tryFire("AdminCash", 1)
        tryFire("AdminCash", 100)
        tryFire("AdminCash", "give")
        
        tryFire("ClaimDaily")
        tryFire("ClaimPlaytimeReward")
        tryFire("ClaimQuest")
        tryFire("GetDailyInfo")
        
        -- Others that might help
        tryFire("EquipPickaxe")
        tryFire("GetActiveBoosts")
        tryFire("GetOwnedPickaxes")
    end)
end

local function stopSpamming()
    spamming = false
    if conn then
        conn:Disconnect()
        conn = nil
    end
    status.Text = "● Idle"
    status.TextColor3 = Color3.fromRGB(170, 170, 180)
end

-- Toggle
toggle.MouseButton1Click:Connect(function()
    enabled = not enabled
    if enabled then
        toggle.Text = "SPAMMING ENABLED (Hold E)"
        toggle.BackgroundColor3 = Color3.fromRGB(65, 185, 85)
    else
        toggle.Text = "ENABLE SPAM"
        toggle.BackgroundColor3 = Color3.fromRGB(40, 40, 48)
        stopSpamming()
    end
end)

-- E Key
UserInputService.InputBegan:Connect(function(input, gp)
    if gp then return end
    if input.KeyCode == Enum.KeyCode.E and enabled then
        startSpamming()
    end
end)

UserInputService.InputEnded:Connect(function(input)
    if input.KeyCode == Enum.KeyCode.E then
        stopSpamming()
    end
end)

-- Close
closeBtn.MouseButton1Click:Connect(function()
    screenGui:Destroy()
end)

print("⛏️ Mining Spammer GUI loaded! Enable then hold E to test all remotes.")
